
ùroot"_tf_keras_model*Ù{"name": "gcn", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "must_restore_from_config": false, "class_name": "GCN", "config": {"n_labels": 7, "channels": 16, "activation": "relu", "output_activation": "softmax", "use_bias": false, "dropout_rate": 0.5, "l2_reg": 0.00025}, "shared_object_id": 0, "is_graph_network": false, "full_save_spec": {"class_name": "__tuple__", "items": [[{"class_name": "__tuple__", "items": [{"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [2708, 1433]}, "float32", "input_1"]}, {"class_name": "TypeSpec", "type_spec": "tf.SparseTensorSpec", "serialized": [{"class_name": "TensorShape", "items": [2708, 2708]}, "float32"]}]}], {}]}, "save_spec": {"class_name": "__tuple__", "items": [{"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [2708, 1433]}, "float32", "input_1"]}, {"class_name": "TypeSpec", "type_spec": "tf.SparseTensorSpec", "serialized": [{"class_name": "TensorShape", "items": [2708, 2708]}, "float32"]}]}, "keras_version": "2.7.0", "backend": "tensorflow", "model_config": {"class_name": "GCN", "config": {"n_labels": 7, "channels": 16, "activation": "relu", "output_activation": "softmax", "use_bias": false, "dropout_rate": 0.5, "l2_reg": 0.00025}}, "training_config": {"loss": {"class_name": "CategoricalCrossentropy", "config": {"reduction": "sum", "name": "categorical_crossentropy", "from_logits": false, "label_smoothing": 0.0, "axis": -1}, "shared_object_id": 1}, "metrics": null, "weighted_metrics": [[{"class_name": "MeanMetricWrapper", "config": {"name": "acc", "dtype": "float32", "fn": "categorical_accuracy"}, "shared_object_id": 2}]], "loss_weights": null, "optimizer_config": {"class_name": "Adam", "config": {"name": "Adam", "learning_rate": 0.009999999776482582, "decay": 0.0, "beta_1": 0.8999999761581421, "beta_2": 0.9990000128746033, "epsilon": 1e-07, "amsgrad": false}}}}2
õroot._d0"_tf_keras_layer*Ï{"name": "dropout", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout", "trainable": true, "dtype": "float32", "rate": 0.5, "noise_shape": null, "seed": null}, "shared_object_id": 3}2
ú
root._gcn0"_tf_keras_layer*Ò{"name": "gcn_conv", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "GCNConv", "config": {"name": "gcn_conv", "trainable": true, "dtype": "float32", "activation": "relu", "use_bias": false, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}, "shared_object_id": 4}, "bias_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 5}, "kernel_regularizer": {"class_name": "L2", "config": {"l2": 0.0002500000118743628}, "shared_object_id": 6}, "bias_regularizer": null, "kernel_constraint": null, "bias_constraint": null, "channels": 16}, "shared_object_id": 7, "build_input_shape": [{"class_name": "TensorShape", "items": [2708, 1433]}, {"class_name": "TensorShape", "items": [2708, 2708]}]}2
ùroot._d1"_tf_keras_layer*Ó{"name": "dropout_1", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_1", "trainable": true, "dtype": "float32", "rate": 0.5, "noise_shape": null, "seed": null}, "shared_object_id": 8}2
°
root._gcn1"_tf_keras_layer*ˆ{"name": "gcn_conv_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "GCNConv", "config": {"name": "gcn_conv_1", "trainable": true, "dtype": "float32", "activation": "softmax", "use_bias": false, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}, "shared_object_id": 9}, "bias_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 10}, "kernel_regularizer": null, "bias_regularizer": null, "kernel_constraint": null, "bias_constraint": null, "channels": 7}, "shared_object_id": 11, "build_input_shape": [{"class_name": "TensorShape", "items": [2708, 16]}, {"class_name": "TensorShape", "items": [2708, 2708]}]}2
¹=root.keras_api.metrics.0"_tf_keras_metric*‚{"class_name": "Mean", "name": "loss", "dtype": "float32", "config": {"name": "loss", "dtype": "float32"}, "shared_object_id": 12}2
á>root.keras_api.metrics.1"_tf_keras_metric*ª{"class_name": "MeanMetricWrapper", "name": "acc", "dtype": "float32", "config": {"name": "acc", "dtype": "float32", "fn": "categorical_accuracy"}, "shared_object_id": 2}2